### PR TITLE
Fix key signature encoding

### PR DESCRIPTION
**Pull request by dirx**
Solves #173

### CODE REVIEW

**Comment by dirx** [comment]
hi @tambien, I would be happy if you would find time for a review.

**Comment by tambien** [comment]
Does the MIDI parser always return either "major" or "minor" is it ever undefined or a different value?

**Comment by dirx** [comment]
The midi-file parser always returns a number (int) value for the event.key and event.scale (in case the format is valid else throws). The parser does not have extra safeguards in place for values not defined in the midi format.

```js
case 0x59:
        event.type = 'keySignature'
        if (length != 2) throw "Expected length for keySignature event is 2, got " + length
        event.key = p.readInt8()
        event.scale = p.readUInt8()
        return event
```

See https://github.com/carter-thaxton/midi-file/blob/f97a02956bdf09b2b72b9f900a82393973681f02/lib/midi-parser.js#L153-L158

Defined range in the midi format for keys is -7 (number of flats) to 7 (number of sharps) and scale 0 (major) and 1 (minor)  - based on reading through https://midiprog.com/midi-key-signature/ and also https://www.midi.org/forum/15035-only-14-key-signature-allowed-in-midi.

Out of range values for keys would map to `undefined` (as before).
Out of range values for scale would always map to `minor` (as before).

Any pointers on how to take care of the out of range values? As before, ignore them completely or eg. map scale also to `undefined`?

**Comment by tambien** [comment]
thank you!

**Pull request merged**
