### PR TITLE
fixed modules

### PR DESCRIPTION
**Pull request by appsforartists**
```javascript
import Util from './Util.js'
```

is not a valid way to import all the exports from a module.  It yields "Cannot find Util.default" in environments that implement the ES modules spec.  This PR implements the correct syntax, and converts Util to use ES module exports like the rest of the package.

### CODE REVIEW

**Comment by tambien** [comment]
thanks! ...but now the tests don't pass anymore.

**Comment by appsforartists** [comment]
Dammit - I forgot to run them…  Grr…

**Comment by appsforartists** [comment]
Should be fixed now.  Sorry about that.

Do you want to merge #27 separately, or do you want a PR with both? 

(Distributing the build in the repo makes PRs hard, because you automatically have merge conflicts on the build.  An alternative would be to use .gitignore and .npmignore to include it in NPM but not in git.)

**Comment by appsforartists** [comment]
https://github.com/appsforartists/MidiConvert/commits/all-the-changes is my branch with everything merged

**Comment by tambien** [comment]
thanks. yeah i think best to ignore the build files to reduce conflicts. maybe we can setup travis to build it and commit the built file somewhere

**Comment by tambien** [comment]
or maybe best is if the build is only accessible through npm install

**Pull request merged**
