### PR TITLE
added track.isPercussion and track.channelNumber

### LINKED ISSUE #13: Is CHANNEL hardcoded?
In `track.encode`, it looks like `CHANNEL` is hardcoded to 0:

https://github.com/Tonejs/MidiConvert/blob/master/src/Track.js#L195

Should this be passed through from `midi.encode`?

```javascript
track.encode(trackEncoder, i, this.header)
```

### PR DESCRIPTION
**Pull request by appsforartists**
As described in https://www.midi.org/specifications/item/general-midi-2, Channels 10-11 (0x9 and 0xA) are reserved for percussion.

Closes #13

### CODE REVIEW

**Comment by appsforartists** [comment]
@tambien This branch should have all of tonight's changes on it.  If you merge this, you can close the other two.

I tend to think/work linearly.  Breaking them out into atomic pieces seemed like it would just add more work for you (because it would introduce merge issues).  Let me know if there are any I need to rebase out.

**Comment by tambien** [comment]
sorry, missed that comment about this including all of the previous PRs in it. seems fine, no merge issues. 

thanks for all of the effort. 

'isPercussion' sounds like more of a getter function in the naming to me, i might change it just to 'percussion'

**Comment by tambien** [comment]
i'm going to keep isPercussion, i think that makes it nice and clear that it's a readyOnly boolean. 

I've moved 'midi.name' into the header with the rest of the file information.

thanks again for all these updates! much appreciated

**Comment by appsforartists** [comment]
Wow; thanks for the fast merge!

`header.name ` seems fine to me.  I only didn't include it there because I didn't know if you wanted it to match the MIDI header.

Speaking of `header`, I've always been curious about `PPQ` and `bpm`.  Shouldn't those be both either upper or lower case?  I don't use them, so I haven't opened a PR for them (it would just be busywork for you to merge, then go change all your code that uses them), but consistency is 👍.

More importantly, are you sure you want to have a truthy default value for `instrument` et. al.?  `undefined` or `''` seem like safer choices, because you can easily `if (instrument)` them, or `midi.instrument || ' whatever fallback you like'`.  Even if a file doesn't set it, any track with notes represents some instrument, so `'none'` doesn't quite feel right to me.

**Comment by tambien** [comment]
oh good point about instrument = 'none'. i'll change that. 

re: PPQ and bpm. those are the way that they are referenced in Tone.js. I will consider making PPQ lowercase to make it more consistent, and if i do, i'll change it here too.

**Comment by appsforartists** [comment]
Thanks.  

Not breaking the ecosystem to be pedantic about features I don't use is exactly why I didn't PR it.  :)

**Pull request merged**
